version: "3.9"

services:
  backend:
    build: ./backend
    container_name: proofpoint-backend
    ports:
      - "3001:3000"
    networks:
      - proofnet

  nginx:
    build: ./nginx
    container_name: proofpoint-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - proofnet

networks:
  proofnet:
    driver: bridge
