version: "3.9"
services:
  proofpoint:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: proofpoint
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: proofpointdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
